 SELECT COALESCE(l4.hostname, l6.hostname) AS hostname,
    upper(COALESCE(l4.hwaddr_fmt, l6.hwaddr_fmt)) AS hwaddr,
    l4.ipv4,
    l6.ipv6,
    l4.clientidv4,
    l6.clientidv6,
    l4.subnet_id_v4,
    l6.subnet_id_v6,
    l4.expire_v4,
    l6.expire_v6,
    l4.valid_lifetime_v4,
    l6.valid_lifetime_v6,
    l4.state_v4,
    l6.state_v6,
    l4.address_raw_v4,
    l6.address_raw_v6
   FROM ( SELECT lease4.hwaddr,
            colonseparatedhex(encode(lease4.hwaddr, 'hex'::text)) AS hwaddr_fmt,
            replace(lease4.hostname::text, ','::text, '&#x2c'::text) AS hostname,
            host('0.0.0.0'::inet + lease4.address) AS ipv4,
            colonseparatedhex(encode(lease4.client_id, 'hex'::text)) AS clientidv4,
            lease4.subnet_id AS subnet_id_v4,
            lease4.expire AS expire_v4,
            lease4.valid_lifetime AS valid_lifetime_v4,
            lease4.state AS state_v4,
            lease4.address AS address_raw_v4
           FROM lease4) l4
     FULL JOIN ( SELECT lease6.hwaddr,
            colonseparatedhex(encode(lease6.hwaddr, 'hex'::text)) AS hwaddr_fmt,
            replace(lease6.hostname::text, ','::text, '&#x2c'::text) AS hostname,
            host(lease6.address) AS ipv6,
            colonseparatedhex(encode(lease6.duid, 'hex'::text)) AS clientidv6,
            lease6.subnet_id AS subnet_id_v6,
            lease6.expire AS expire_v6,
            lease6.valid_lifetime AS valid_lifetime_v6,
            lease6.state AS state_v6,
            host(lease6.address) AS address_raw_v6
           FROM lease6) l6 ON l4.hwaddr = l6.hwaddr
  ORDER BY (COALESCE(l4.hostname, l6.hostname)), (COALESCE(l4.hwaddr_fmt, l6.hwaddr_fmt));
