# Generated by Django 5.1.5 on 2025-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease4',
            fields=[
                ('address', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hwaddr', models.BinaryField(blank=True, null=True)),
                ('client_id', models.BinaryField(blank=True, null=True)),
                ('valid_lifetime', models.BigIntegerField(blank=True, null=True)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('subnet_id', models.BigIntegerField(blank=True, null=True)),
                ('fqdn_fwd', models.BooleanField(blank=True, null=True)),
                ('fqdn_rev', models.BooleanField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.BigIntegerField(default=0)),
                ('user_context', models.TextField(blank=True, null=True)),
                ('relay_id', models.BinaryField(blank=True, null=True)),
                ('remote_id', models.BinaryField(blank=True, null=True)),
                ('pool_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'lease4',
                'managed': False,
            },
        ),
    ]
